import os
import requests
import re

def get_pdb_sequence(pdb_id):
    url = f"https://data.rcsb.org/rest/v1/core/entry/{pdb_id}"
    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            # This is a simplified fetch, real RCSB API requires entity level for sequence
            # But we can try the fasta endpoint
            fasta_url = f"https://www.rcsb.org/fasta/entry/{pdb_id}"
            fasta_res = requests.get(fasta_url)
            if fasta_res.status_code == 200:
                lines = fasta_res.text.splitlines()
                seq = "".join(l.strip() for l in lines if not l.startswith(">"))
                return seq
    except:
        pass
    return None

# Top targets (Difficult, Knotted, Orphans, GPCRs)
targets = [
    ("Insulin", "GIVEQCCTSICSLYQLENYCNFVNQHLCGSHLVEALYLVCGERGFFYTPKT"),
    ("Ubiquitin", "MQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRLRGG"),
    ("Lysozyme", "KVFERCELARTLKRLGMDGYRGISLANWMCLAKWESGYNTRATNYNAGDRSTDYGIFQINSRYWCNDGKTPGAVNACHLSCSALLQDNIADAVACAKRVVRDPQGIRAWVAWRNRCQNRDVRQYVQGCGV"),
    ("BPTI", "RPDFCLEPPYTGPCKARIIRYFYNAKAGLCQTFVYGGCRAKRNNFKSAEDCMRTCGGA"),
    ("Myoglobin", "MGLSDGEWQLVLNVWGKVEADIPGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGATVLTALGGILKKKGHHEAEIKPLAQSHATKHKIPVKYLEFISECIIQVLQSKHPGDFGADAQGAMNKALELFRKDMASNYKELGFQG"),
    ("p53 DNA-binding", "MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPRMPEAAPPVAPAPAAPTPAAPAPAPSWPLSSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLRKKGEPHHELPPGSTKRALPNNTSSSPQPKKKPLDGEYFTLQIRGRERFEMFRELNEALELKDAQAGKEPGGSRAHSSHLKSKKGQSTSRHKKLMFKTEGPDSD"),
    ("Rhodopsin (GPCR)", "MNGTEGPNFYVPFSNKTGVVRSPFEAPQYYLAEPWQFSMLAAYMFLLIMLGFPINFLTLYVTVQHKKLRTPLNYILLNLAVADLFMVFGGFTTTLYTSLHGYFVFGPTGCNLEGFFATLGGEIALWSLVVLAIERYVVVCKPMSNFRFGENHAIMGVAFTWVMALACAAPPLVGWSRYIPEGMQCSCGIDYYTPHEETNNESFVIYMFVVHFIIPLIVIFFCYGQLVFTVKEAAAQQQESATTQKAEKEVTRMVIIMVIAFLICWLPYAGVAFYIFTHQGSDFGPIFMTIPAFFAKTSAVYNPVIYIMMNKQFRNCMVTTLCCGKNPLGDDEASATASKTETSQVAPA"),
    ("Top7 (Designed)", "MGDIQVQVNIDDNGKNFDYTYTVTTESELQKVLNELMDYIKKQGAKRVRISITARTKKEAEKFAAILIKVFAELGYNDINVTFDGDTVTVEGQLEGGSLEHHHHHH"),
    ("ORF8 (SARS-CoV-2)", "MKFLVFLGIITTVAAFHQECSLQSCTQHQPYVVDDPCPIHFYSKWYIRVGARKSAPLIELCVDEAGSKSPIQYIDIGNYTVSCLPFTINCQEPKLGSLVVRCSFYEDFLEYHDVRVVLDFI"),
    ("TRPV1", "MKKWSSTDLGAAADPLQKDTCPDPLDGDPNSRPPPAKPQLSTAKSRTRLFGKGDSEEASPLDCPYEEGGLASCPIITVSSVLTIQRPGDGPASVRAASQDSVAASTEKTLRLYDRRSIFEAVAQNNCQDLESLLLFLQKKSKKLPVDRNIAFRNYDLLFGTTRLCPGNNFEGLVNYGLLVDLHLLLQKKCHLPTTPHCSSTSPVLPTRPTPHCTPTPSTPSTPSTPSTPST"),
    ("Abeta42", "DAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIA"),
    ("Titinfold", "LIEVEKPLYGVEVFVGETAHFEIELSEPDVHGQWKLKGQPLTASPDCEIIEDGKKHILILHNCQLGMTGEVSFQAANTKSAANLKVKEL")
]

# Generate 100 random difficult sequences using biased compositions
import random

def gen_tough_seq(length):
    # Biased towards hydrophobic and cysteine for difficulty
    aas = "ACDEFGHIKLMNPQRSTVWY"
    weights = [10, 5, 2, 2, 2, 5, 5, 2, 10, 10, 2, 5, 5, 5, 5, 5, 5, 10, 2, 2]
    return "".join(random.choices(aas, weights=weights, k=length))

for i in range(13, 101):
    l = random.randint(30, 150)
    targets.append((f"Tough-Target-{i}", gen_tough_seq(l)))

print("PROTEIN_LIBRARY = {")
for name, seq in targets:
    print(f'    "{name}": {{"seq": "{seq}"}},')
print("}")
