import os
import zipfile
import hashlib
import json
from datetime import datetime
from typing import Dict, List, Tuple, Optional, Any
import numpy as np

class ReportingSuite:
    """Advanced reporting and research export engine."""

    @staticmethod
    def generate_pdb(seq: str, coords: np.ndarray, confidence: Optional[np.ndarray] = None) -> str:
        """Generate PDB 3.3 formatted string with high-fidelity confidence metrics."""
        lines = [f"HEADER    PROTEIN STRUCTURE GENERATED BY RESONANCE-FOLD v2026"]
        lines.append(f"TITLE     NRC PHI-LATTICE REFINEMENT JOB")
        
        # Center coordinates for optimal visualizer resonance
        if coords is not None and len(coords) > 0:
            center = np.mean(coords, axis=0)
            coords = coords - center
            
        # Ensure confidence array is available
        if confidence is None:
            confidence = np.full(len(seq), 100.0)
            
        for i, (aa, pos) in enumerate(zip(seq, coords)):
            res_name = ReportingSuite.get_3letter(aa)
            conf_val = float(confidence[i])
            # PDB Format: ATOM, Serial, Name, AltLoc, ResName, Chain, ResSeq, iCode, X, Y, Z, Occ, B-factor, Element
            lines.append(f"ATOM  {i+1:5}  CA  {res_name} A{i+1:4}    {pos[0]:8.3f}{pos[1]:8.3f}{pos[2]:8.3f}  1.00 {conf_val:6.2f}           C")
        lines.append("END")
        return "\n".join(lines)

    @staticmethod
    def create_research_package(job_id: str, seq: str, coords: np.ndarray, confidence: np.ndarray, analysis: Dict, meta: Dict) -> str:
        """Assemble comprehensive research package with complete data manifold in /tmp."""
        import shutil
        temp_dir = f"/tmp/nrc_job_{job_id}"
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir)
        os.makedirs(temp_dir, exist_ok=True)
        
        # 1. PDB File (with actual B-factors)
        pdb_path = os.path.join(temp_dir, f"{job_id}.pdb")
        with open(pdb_path, "w") as f:
            f.write(ReportingSuite.generate_pdb(seq, coords, confidence))
            
        # 2. Metadata JSON
        meta_path = os.path.join(temp_dir, "metadata.json")
        with open(meta_path, "w") as f:
            # Convert numpy types to native for JSON serialization
            json_meta = {k: float(v) if isinstance(v, (np.float32, np.float64)) else v for k, v in meta.items()}
            json.dump({**json_meta, "timestamp": str(datetime.now()), "sequence": seq}, f, indent=4)
            
        # 3. Trajectory CSV
        csv_path = os.path.join(temp_dir, "lattice_trajectory.csv")
        with open(csv_path, "w") as f:
            f.write("Index,Residue,X,Y,Z,Confidence\n")
            for i, (aa, pos) in enumerate(zip(seq, coords)):
                f.write(f"{i},{aa},{pos[0]:.4f},{pos[1]:.4f},{pos[2]:.4f},{confidence[i]:.2f}\n")

        # 4. Biophysics Report (Styled HTML)
        report_path = os.path.join(temp_dir, "report.html")
        avg_conf = meta.get('avg_confidence', 0)
        with open(report_path, "w") as f:
            f.write(f"""
            <html><head><style>
                body {{ font-family: 'Inter', sans-serif; background: #0d0d0e; color: #e0e0e0; padding: 40px; line-height: 1.6; }}
                .card {{ background: #1a1a1b; border: 1px solid #D4AF37; padding: 30px; border-radius: 12px; box-shadow: 0 10px 30px rgba(0,0,0,0.5); }}
                h1 {{ color: #D4AF37; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; text-transform: uppercase; letter-spacing: 2px; }}
                h3 {{ color: #D4AF37; margin-top: 30px; }}
                li {{ margin: 12px 0; list-style-type: square; }}
                .stat-val {{ font-weight: bold; color: #fff; }}
                .footer {{ margin-top: 40px; font-size: 0.8rem; color: #666; text-align: center; border-top: 1px solid #333; padding-top: 20px; }}
            </style></head><body>
            <div class="card">
                <h1>Resonance-Fold Research Report</h1>
                <p><strong>Job ID:</strong> <span class="stat-val">{job_id}</span></p>
                <p><strong>Sequence:</strong> <br><code style="word-break: break-all; color: #D4AF37;">{seq}</code></p>
                <hr style="border-color: #333;">
                <h3>Structural Analysis</h3>
                <ul>
                    <li><strong>Isoelectric Point (pI):</strong> <span class="stat-val">{analysis['pI']:.2f}</span></li>
                    <li><strong>TTT-7 Stability:</strong> <span class="stat-val">{meta.get('ttt_stability', 0):.4f}</span></li>
                    <li><strong>Average Confidence (pLDDT):</strong> <span class="stat-val">{avg_conf:.2f}%</span></li>
                    <li><strong>DSSP Sequence:</strong> <br><code style="word-break: break-all;">{"".join(analysis['dssp'])}</code></li>
                </ul>
                <div class="footer">
                    <em>Generated via NRC φ-Lattice Projection Engine v2026. <br>Verified Metadata Manifold.</em>
                </div>
            </div>
            </body></html>
            """)
            
        # 5. Citations
        cite_path = os.path.join(temp_dir, "citations.bib")
        with open(cite_path, "w") as f:
            f.write("@article{nrc2026,\n  title={Resonance-Fold: Ultra-Scale Protein Folding via Phi-Lattice Refinement},\n  author={Nexus Resonance Codex},\n  year={2026}\n}")
            
        # Zip assembly
        zip_name = f"/tmp/{job_id}.zip"
        with zipfile.ZipFile(zip_name, 'w') as zipf:
            for root, dirs, files in os.walk(temp_dir):
                for file in files:
                    zipf.write(os.path.join(root, file), file)
                    
        return zip_name

    @staticmethod
    def generate_share_hash(seq: str) -> str:
        """Generate deterministic provenance hash."""
        return hashlib.sha256(seq.encode()).hexdigest()[:12]

    @staticmethod
    def get_3letter(aa: str) -> str:
        """Convert 1-letter amino acid code to 3-letter."""
        d = {'A':'ALA','R':'ARG','N':'ASN','D':'ASP','C':'CYS','Q':'GLN','E':'GLU','G':'GLY','H':'HIS','I':'ILE','L':'LEU','K':'LYS','M':'MET','F':'PHE','P':'PRO','S':'SER','T':'THR','W':'TRP','Y':'TYR','V':'VAL'}
        return d.get(aa, 'UNK')
