import os
import zipfile
import hashlib
import json
from datetime import datetime
from typing import Dict, List, Tuple
import numpy as np

class ReportingSuite:
    """Institutional-grade reporting and export engine."""

    @staticmethod
    def generate_pdb(seq: str, coords: np.ndarray) -> str:
        """Generate PDB 3.3 formatted string."""
        lines = [f"HEADER    PROTEIN STRUCTURE GENERATED BY RESONANCE-FOLD v2026"]
        lines.append(f"TITLE     NRC PHI-LATTICE REFINEMENT JOB")
        for i, (aa, pos) in enumerate(zip(seq, coords)):
            res_name = ReportingSuite.get_3letter(aa)
            lines.append(f"ATOM  {i+1:5}  CA  {res_name} A{i+1:4}    {pos[0]:8.3f}{pos[1]:8.3f}{pos[2]:8.3f}  1.00  0.00           C")
        lines.append("END")
        return "\n".join(lines)

    @staticmethod
    def create_research_package(job_id: str, seq: str, coords: np.ndarray, analysis: Dict, meta: Dict) -> str:
        """Assemble institutional .zip package."""
        temp_dir = f"temp_{job_id}"
        os.makedirs(temp_dir, exist_ok=True)
        
        # 1. PDB File
        pdb_path = os.path.join(temp_dir, f"{job_id}.pdb")
        with open(pdb_path, "w") as f:
            f.write(ReportingSuite.generate_pdb(seq, coords))
            
        # 2. Metadata JSON
        meta_path = os.path.join(temp_dir, "metadata.json")
        with open(meta_path, "w") as f:
            json.dump({**meta, "timestamp": str(datetime.now()), "sequence": seq}, f, indent=4)
            
        # 3. Biophysics Report (Markdown/HTML)
        report_path = os.path.join(temp_dir, "report.html")
        with open(report_path, "w") as f:
            f.write(f"<h1>Resonance-Fold Research Report</h1><p>Job: {job_id}</p>")
            f.write(f"<h3>Biophysical Metrics</h3><ul><li>pI: {analysis['pI']}</li></ul>")
            
        # 4. Citations
        cite_path = os.path.join(temp_dir, "citations.bib")
        with open(cite_path, "w") as f:
            f.write("@article{nrc2026,\n  title={Resonance-Fold: Ultra-Scale Protein Folding via Phi-Lattice Refinement},\n  author={Nexus Resonance Codex},\n  year={2026}\n}")
            
        # Zip assembly
        zip_name = f"{job_id}.zip"
        with zipfile.ZipFile(zip_name, 'w') as zipf:
            for root, dirs, files in os.walk(temp_dir):
                for file in files:
                    zipf.write(os.path.join(root, file), file)
                    
        return zip_name

    @staticmethod
    def generate_share_hash(seq: str) -> str:
        """Generate deterministic provenance hash."""
        return hashlib.sha256(seq.encode()).hexdigest()[:12]

    @staticmethod
    def get_3letter(aa: str) -> str:
        """Convert 1-letter amino acid code to 3-letter."""
        d = {'A':'ALA','R':'ARG','N':'ASN','D':'ASP','C':'CYS','Q':'GLN','E':'GLU','G':'GLY','H':'HIS','I':'ILE','L':'LEU','K':'LYS','M':'MET','F':'PHE','P':'PRO','S':'SER','T':'THR','W':'TRP','Y':'TYR','V':'VAL'}
        return d.get(aa, 'UNK')
